### PR TITLE
Adds auto_set_content_size for UIScrollview and subclasses.

### PR DESCRIPTION
**Pull request by markrickert**
So that you can add a bunch of things to a scrollview and then call auto_set_content_size and it will not change frame but automatically set the `contentSize` based on the scroll view's contents (with optional padding)

### CODE REVIEW

**Comment by markrickert** [comment]
Once #195 is merged, I'll modify this PR to pull out the subview size calculation into its own method so that it's not repeated in both `auto_set_content_size` & `resize_to_fit_subviews`

**Comment by GantMan** [comment]
This is awesome.

I'd like to bring up a major issue that is starting to rear it's head.  @twerth your feedback on this idea would be most appreciated.

this is `auto_set_content_size`
on labels we have `resize_to_fit_text` alias `size_to_fit`
and on UIViews we have `resize_to_fit_subviews `

Since Mark's code here is not actually resizing a scrollview, should we possibly add aliases to the others, taking the `auto_set` prefix?

### It would be nice to add some conformity in this
We remember one method that changes depending on the object.  **I'm going to suggest** `auto_set_content_size` and `auto_set_frame_size` as the 2 options.

**Comment by twerth** [comment]
I agree to having some conformity in these names. 

IMO, auto_set_content_size means it will automatically set content size when something happens. That's the way I read it. I'd rather that be named something that suggests it's going to happen right now and only right now.

**Comment by markrickert** [comment]
I see your point. I picked "auto_set" because it automatically sets it based on the subviews. I'm open to a different name though :+1:

**Comment by twerth** [comment]
I'd actually like to eventually have an "auto_set" where it does automaticallyl set it when something changes. But that's a bigger feature. 

Imagine you do this `st.auto_resize_to_fit_children = true` and anytime a child's frame changes it sets the parent if needed and applicable

**Comment by twerth** [comment]
It's long, but how about: `resize_content_to_fit_subviews` assuming that's exactly what it does. 

I'm a big believer in "make a method name as short as possible and be completely clear, and no shorter"

**Comment by GantMan** [comment]
Also, `resize_to_fit_subviews` will need documentation on the site along side with whatever the name ends up being.  

I'm :+1: with `resize_content_to_fit_subviews`.

Playing with :fire: 
What about `view_refit` and `content_refit` ?
It meets all needs.  Name says what it is, and it's short.  Feels clean to me.

**Comment by twerth** [comment]
I personally don't like `view_refit`, it's a bit unclear, but I'm curious what Mark thinks.

**Comment by markrickert** [comment]
I'm not a fan of the shorter name. not descriptive enough. It's a complex task we're trying to describe in just a few words.

if we're gonna go with `resize_content_to_fit_subviews` we should also change the name of the other method to `resize_frame_to_fit_subviews`, no?

**Comment by GantMan** [comment]
/giphy Take my ball and go home.

**Comment by twerth** [comment]
Yeah, that makes sense @markrickert. I like that. Leave the alias for now though for backwards compatibility.

**Comment by markrickert** [comment]
Cool. I've renamed the method as well as changing the frame setter and creating an alias to the old method.

**Comment by markrickert** [comment]
Tests passed :)

**Comment by markrickert** [comment]
New feature for `resize_frame_to_fit_subviews`:

Allows you to pass `:only_width` or `:only_height` so that things aren't resized that you don't want to be :)

Useful for when you have views inside a uiview that don't extend all the way to the right and you only want to resize the height of the frame.

**Comment by markrickert** [comment]
@GantMan @twerth i think this one is ready to go. 3 new tests with 26 new assertions!

I'll write documentation once it's merged and a new version is released.

**Comment by GantMan** [comment]
Mark adding tests: 

nice tests bro

**Comment by markrickert** [comment]
lol

**Comment by GantMan** [comment]
Hey @markrickert I just searched for this today on the docs.  Let me know if you want any help adding them!   I need to go through anyway and add docs for my stuff.

**Pull request merged**
