### PR TITLE
fixed slide-in animation with help from @twerth

### PR DESCRIPTION
**Pull request by kevinvangelder**
All specs pass.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
:+1:

**Comment by carlinisaacson** [comment]
Looks good. What was the issue you were trying to fix? I don't remember slide_in being broken when I used it.

**Comment by kevinvangelder** [comment]
There were two issues here. In our implementation we called `append(...).hide.animations.slide_in` but `slide_in` wasn't calling `show` (but `slide_out` was calling hide, so even if we hadn't hidden it the problem would still show up if you slide in, out, and back in again).

The second issue was that `start_frame` was a reference to `bq`, so the modified `bq` was returned at the end of the block instead of the appropriate unmodified copy of `bq` that `start_frame` was intended to be.

**Comment by carlinisaacson** [comment]
:+1:

**Pull request merged**
