### PR TITLE
Properly work with the gradient layer if exists

### PR DESCRIPTION
**Pull request by squidpunch**
this should fix the gradient issues reported in #198 

Note: I didnt update the rest of the view issues we were seeing @twerth @GantMan

### CODE REVIEW

**Comment by squidpunch** [comment]
hey @GantMan give this a look, could you?  I realize that without this fix, when rotating the device we are  adding layer after layer to the view... :open_mouth:

**Comment by GantMan** [comment]
gradient works great!   What do you propose we do for positioning this on rotation?

**Comment by twerth** [comment]
Just move it somewhere, or we can relay out that whole thing. Or frankly, you can just leave it, it's not a big deal

**Comment by GantMan** [comment]
Yeah, either way it shouldn't hold up this PR.   Good fix Squid.

**Pull request merged**
