### PR TITLE
Added left and right view modes to UITextViews

### PR DESCRIPTION
**Pull request by GantMan**
Symbol friendly left and right view modes with symbol support.

### CODE REVIEW

**Comment by markrickert** [comment]
Why not just 

```ruby
view.leftViewMode = TEXT_FIELD_MODES[v] || v
```

?

**Comment by GantMan** [comment]
I was very sleepy.....    Indeed mr. Rickert... indeed.   This will be fixed soon.

**Comment by GantMan** [comment]
ummmmm Travis screwed up?

**Comment by markrickert** [comment]
I restarted the build for ya.

**Comment by markrickert** [comment]
:+1:

**Pull request merged**
