### PR TITLE
Custom events and trigger

### PR DESCRIPTION
**Pull request by bmichotte**
Allow the use of .on() with some custom event. Also add a trigger() on views.

You can now use something like 
```
append(UIView).on(:my_event) {|o| }

rmq(UIView).trigger(:my_event)
```

### CODE REVIEW

**Comment by GantMan** [comment]
I love this idea.

**Comment by squidpunch** [comment]
:+1:

**Comment by twerth** [comment]
This is awesome Benjamin, let me check the code real quick

**Comment by jamonholmgren** [comment]
Love it.

**Comment by twerth** [comment]
Benjamin merged. You get a high four for that http://ir_public.s3.amazonaws.com/slack/high_four.jpg

It would be uber cool, if you could add docs to RedPotion's event docs also: https://github.com/infinitered/redpotion/blob/master/docs/cookbook/events_and_gestures.md

**Comment by bmichotte** [comment]
@twerth i'll do that

**Comment by twerth** [comment]
Something is broken with this, I'm debugging now

**Comment by bmichotte** [comment]
I'm using it atm, what is broken ?

**Comment by twerth** [comment]
sender is an RMQ object

```    @vc.rmq(view).on(:custom) do |sender|
      sender.should == view
      some_value = true
    end``` 

is test I just created, it's failing

**Comment by twerth** [comment]
or is it suppose to return the rmq object? Hmm, I may be totally wrong on that

**Comment by bmichotte** [comment]
Hmm, no, you're right, it should be
```
events(view)[event].block.call(self.get) if events(view)[event]
```

on events.rb:111

**Comment by twerth** [comment]
Nevermind, I have another test that says it should be the view wrapped in an RMQ object. It's been a while since I wrote this (events were actually the very first thing I wrote for RMQ). My mistake, sorry.

**Comment by twerth** [comment]
Small fix: https://github.com/infinitered/rmq/commit/0606d93c86102ff4756e27a8b0a6b124915e134a

**Comment by twerth** [comment]
FYI, there are some other issues, user_interaction is enabled on a custom event, this causes issue. I'm also checking the the event state is correct on custom events. I'm working on tests and fixes for this

**Comment by bmichotte** [comment]
Mhh, sorry @twerth, tests were running fine, I thought I had broken anything :/

**Comment by twerth** [comment]
No worries Ben. I was just poking around and noticed somethings that were off. It's a great feature and the community will really appreciate you created it.

**Comment by squidpunch** [comment]
I'd love to see an example of what you guys are doing with custom events like this! :)

**Comment by bmichotte** [comment]
@squidpunch The simplest example of the world :)

I've a "button" and only want to allow tap on part of this view

```ruby
# Screen
append(Button, :style).on(:tapped) do |sender|
       # i've been tapped
end

# Button < UIView
def on_load
   append(UIImageView, :bg).on(:tap) do |_|
        find(self).trigger(:tapped)
   end
end

# style
def bg(st)
     st.frame = {l: 30, t: 30, fr: 30, fb: 30 }
end
```

**Comment by squidpunch** [comment]
oh ok, i gotcha - cool, thanks @bmichotte

**Comment by bmichotte** [comment]
You can also imagine something like (web browser)

```ruby
def on_load
   append(UITextField, :url_field)

   append(UIWebView, :web).on(:goto_url) do |sender|
        url = find(:url_field).data # not sure about the .data, i'm new to redpotion :p
        sender.loadRequest url.nsurl.nsurlrequest # using sugarcube
   end
     
   append(UIButton).on(:tap) do
       find(:web).trigger(:goto_url)
   end
end
```

I find this very elegant, more then 
```ruby
def on_load
   append(UITextField, :url_field)
   append(UIWebView, :web)
   append(UIButton).on(:tap) do
       goto_url
   end
end

def goto_url
   url = find(:url_field).data
   find(:web).get.loadRequest url.nsurl.nsurlrequest 
end

```

**Comment by jamonholmgren** [comment]
I do this all the time with jQuery, so it's a natural fit here.

**Comment by twerth** [comment]
FYI some more fixes and tests: https://github.com/infinitered/rmq/commit/06885808f5421eac96a4918f62af2370750df1fa

**Comment by bmichotte** [comment]
Waow, nice :)

**Comment by vaughankg** [comment]
Hey @bmichotte, @twerth , I don't believe that this commit is correct: 0606d93

For non-custom/regular events `sender` is not a rmq object.

**Pull request merged**
