### PR TITLE
Adds indicator_style for UIScrollView

### PR DESCRIPTION
**Pull request by markrickert**
Tests failing for some reason. I'm not sure why. Anyone care to take a look? I've verified that it's working in an app I'm working on, but the spec seems to see a different constant.

### CODE REVIEW

**Comment by markrickert** [comment]
Also... not sure why travis didn't catch this pull request.

**Comment by squidpunch** [comment]
image

image

**Comment by squidpunch** [comment]
I will try to look at it tonight / early tomorrow @markrickert

**Comment by markrickert** [comment]
Thank you, Mr. Punch.

Like i said... it's working, but the specs are failing for some reason.

**Comment by squidpunch** [comment]
yeah specs are awesome, until they are annoying - but yeah I'll kick it around and see if i can see whats going on with the test :+1:

**Pull request merged**
