### PR TITLE
Only animate if voiceover is not turned on

### LINKED ISSUE #277: Add accessibility to RMQ Animations
Use `UIAccessibilityIsVoiceOverRunning()` to detect if voiceover is on and if so, don't actually animate the object(s), just change the state(s) and run the callbacks.

From @amirrajan's RubyMotion #Inspect2015 talk - if you animate controls, they're not available for swiping in voiceover mode for the blind.

cc/ @austinseraphin - we missed you this year at Inspect!

### PR DESCRIPTION
**Pull request by squidpunch**
Fixes #277 - really unsure how to best test this...thoughts @markrickert ?

### CODE REVIEW

**Comment by twerth** [comment]
This is awesome. Can we have tests?

**Comment by squidpunch** [comment]
Yeah not sure how to test it. I suppose I can pull in motion stump and stub a bit to get the coverage.

**Comment by markrickert** [comment]
We just need a way so that rmq.accessability.voiceover_enabled? always returns true. Also, note you have a typo in two method names in Accessability.

**Comment by squidpunch** [comment]
That's what happens when you code late nights in Paris night before your flight :)

I'll fix the spelling and work out a few tests as well!

**Comment by squidpunch** [comment]
@markrickert @twerth updated with tests  (and spelling fix thanks mark!) - give it another review :)

**Pull request merged**
