### PR TITLE
Add ability for new iPhone sizes to resource_for_device and tests

### PR DESCRIPTION
**Pull request by fvonhoven**
And the corresponding Default images to the Resources folder for tests

### CODE REVIEW

**Comment by twerth** [comment]
@fvonhoven you accidentally added some images, would you remove those from the commit and update this PR please.

**Comment by squidpunch** [comment]
@twerth I think they were intentional, maybe for the 6 and 6 plus sizes?  I dont have the sizes in front of me to confirm, but I think that was the intent.

**Comment by GantMan** [comment]
yeah, seems those are needed for proper testing.

**Comment by twerth** [comment]
Yes, right, I'm sorry Frank, I'll merge now.

**Pull request merged**
