### PR TITLE
ProjectRootPath

### PR DESCRIPTION
**Pull request by zhigang1992**
Just right in front of me this whole time... :smile: 
@twerth

### CODE REVIEW

**Comment by twerth** [comment]
This is great, does it work as a gem?

**Comment by zhigang1992** [comment]
Hell Yeah...

**Comment by twerth** [comment]
Cool beans. This is awesome.

**Comment by jamonholmgren** [comment]
I was literally going into the gem to add this just now and found out someone else beat me to it. Thanks @zhigang1992 !

**Comment by jamonholmgren** [comment]
`File.expand_path(@project_dir)` also works.

**Pull request merged**
