### PR TITLE
Fix ColorFactory.from_base_color for 32-bit hardware

### PR DESCRIPTION
**Pull request by mwise**
This PR fixes a bug where using any methods that call down to `ColorFactory.from_base_color` would blow up on 32-bit hardware.  To reproduce the bug, just uncomment the `sdk_version` and `deployment_target` directives in the Rakefile and run `rake spec:device` with a non-64-bit device (e.g. iPhone 4s) attached. You should see the following error:
```
TypeError: expected instance of Pointer of type `f', got `d'
```

I couldn't find a good way of reliably testing the architecture flags in the app code, so I thought a begin/rescue might work. It might not be the optimal approach, but it fixed the issue and lets you use all the rmq color code without modification.

Please let me know if there's anything that needs changing or if there is a better way to handle this.

### CODE REVIEW

**Comment by GantMan** [comment]
I'm having trouble understanding the base of the issue.   What are the consequences of `f` and `d` ?

Perhaps @squidpunch can elaborate, since he worked with color a bit.

**Comment by mwise** [comment]
It seems to me that the `UIColor.getRed(r, green: g, blue: b, alpha: a)` method signature is slightly different when running in 32- vs. 64-bit mode. The `f` and `d` refer to Float and Double pointers, respectively.

**Comment by squidpunch** [comment]
so I was about to reply but @mwise already said what I was going to say.  Documentation says that it should be returning a float - so I have no idea why the pointers would be different...

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIColor_Class/#//apple_ref/occ/instm/UIColor/getRed:green:blue:alpha:

**Comment by twerth** [comment]
@squidpunch, should I merge this and and PR(#193)?

**Comment by squidpunch** [comment]
I dont have a 4S to test what this is supposed to fix, and I am a bit surprised the pointer return is different than the docs - however it looks like it works so I think this can be merged.  will review / comment on the other PR separately

**Comment by GantMan** [comment]
Accidentally duplicated.   See comments in #209

**Pull request closed without merging**
