### PR TITLE
Adds w: :full and h: :full

### PR DESCRIPTION
**Pull request by markrickert**
So you can set a frame like:

```ruby
st.frame = {
  bp: 20,
  w: :full,
  h: 20,
  padding: 10
}
```

### CODE REVIEW

**Comment by GantMan** [comment]
thumb-is-up

**Comment by twerth** [comment]
Some notes on this:

superview already exists in that method: `sv`

**Comment by markrickert** [comment]
Aha. yeah. that definitely makes sense. So at the beginning, for all values we look to see if the superview exists and if not, we cry fowl if there's a symbol for the value instead of a number. We can calculate the superview's half, and quarter at the top for reuse on all values further down the chain.

**Comment by twerth** [comment]
@markrickert do you want to work on this or would you prefer me to? Either way is cool to me.

**Comment by markrickert** [comment]
If you've got time to finish what I started, feel free!

**Comment by markrickert** [comment]
@todd Can you take a look at this? i think this should be ready for primetime. I'm not sure what you meant above by "it would be great if this applied to any value, not just for width and height"... what other values might it apply to?

**Comment by twerth** [comment]
Left, top, etc.

`l: :half, t: :quarter`

**Comment by GantMan** [comment]
image

saw this and figured you guys would appreciate it here :)

**Comment by twerth** [comment]
Sorry, not sure where we are on this, @markrickert?

**Comment by squidpunch** [comment]
@markrickert @twerth I can throw a commit in that does `left`, and `top` etc.  If you want?

I think `:full` in these contexts seems a bit weird, but since they all work the same it would probably still be there

**Comment by twerth** [comment]
That'd be great David. Be mindful with performance in this method as it's used a lot.

**Comment by squidpunch** [comment]
I'll try and get some benchmarks before changes and after to get a good idea of performance impact :+1:

**Comment by squidpunch** [comment]
@twerth / @markrickert  to make sure I get this right, what would you expect the values to be for these examples....

```ruby
parent = [[0,0], [12,12]]

child.frame = { l: : full } # origin.x == 0, or 12 ?  full likely means the x value should start at x with a width of 12. but then is this the same for others?

child.frame = { l: : half } # origin.x == 6 ?  Its weird if the full is 0, but this is 6.... ?
child.frame = { l: : quarter } # origin.x == 3 ? same as above?  or does l: : full just not make sense
```

so these questions exist for the other positions as well, so not adding examples, but the same questions are here for 'r', etc  `r: :full`, `r: :half`...whats the proper location?

**Comment by markrickert** [comment]
Those questions are why I only really like these symbol shortcuts for width and height. I don't understand how it would even work for `l:`, `t:`, `fr:`, etc.

**Comment by squidpunch** [comment]
@markrickert agreed, I figured that was the case, we'll see what @twerth has in mind then.

**Comment by twerth** [comment]
Sorry, I missed these comments.

So for horizontal things:

* :full = st.super_frame.width
* :half = st.super_frame.width / 2
* :quarter = st.super_frame.width / 4

For vertical things it would be:

* :full = st.super_frame.height
* :half = st.super_frame.height / 2
* :quarter = st.super_frame.height / 4

Basically I want a button to start at the halfway mark I'd do:

```ruby
st.frame = {l: :half, fr: 0}
```

Does that seem useful?

**Comment by squidpunch** [comment]
yeah thats where our question comes from I think @twerth . `{l: :half}' seams reasonable, but I have  a hard time making a case for `{l: :full}` for example.  There are probably edge cases where you line a view up on the right of the viewport and swipe it in, but I dont know how used it would be?

**Comment by twerth** [comment]
l: :full I can't see really. But you never know you may want it to start off screen. I don't see why we'd limit it. Basically the values are an integer, float, or one of these symbols.

l: half was an actual use case Jamon was asking about.

**Comment by squidpunch** [comment]
@twerth totally agree, I dont think `l: :full` makes sense really or will be used, but its nice to keep a standard interface - I will dust off my branch I started on this soon, and get something out for review!

**Comment by squidpunch** [comment]
just put a PR against this branch to add the extended changes we talked about @twerth @markrickert 

When I can find a bit more time, I can use the benchmark gem to compare my version against what is there to verify I'm not adding any extra processing load.

**Pull request merged**
